# Project: heapsort
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = heapSort.o
LINKOBJ  = heapSort.o
LIBS     = -L"D:/360Downloads/Dev-Cpp/MinGW64/lib" -L"D:/360Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/360Downloads/Dev-Cpp/MinGW64/include" -I"D:/360Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/360Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"D:/360Downloads/Dev-Cpp/MinGW64/include" -I"D:/360Downloads/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/360Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"D:/360Downloads/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = heapsort.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

heapSort.o: heapSort.c
	$(CC) -c heapSort.c -o heapSort.o $(CFLAGS)
